# Generated by Django 5.1.7 on 2025-03-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
