# Generated by Django 5.1.7 on 2025-03-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_cost_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('investor', 'property')},
        ),
    ]
