# Generated by Django 5.1.7 on 2025-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_investment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_tier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shortlet_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
