# Generated by Django 5.1.7 on 2025-03-23 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_membership_expires_at_user_membership_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='converted_to_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gift',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
