# Generated by Django 5.1.7 on 2025-03-23 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_id', models.URLField()),
                ('cac_certificate', models.URLField()),
                ('proof_of_location', models.URLField()),
                ('property_ownership_doc', models.URLField()),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
