# Generated by Django 5.1.7 on 2025-03-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agentverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentverification',
            name='was_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
