# Generated by Django 5.1.7 on 2025-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agentverification_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='withdrawal_requested',
            field=models.BooleanField(default=False),
        ),
    ]
