# Generated by Django 5.1.7 on 2025-03-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_was_verified_as_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
