# Generated by Django 5.1.7 on 2025-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_booking_tx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
